### ISSUE TITLE
能不能发一个数据集的样本例子

### ISSUE THREAD

**Issue by MonkeyDong** [Biuuuuuuuu/CYK-parser#1]
ruleT.txt是什么样的数据格式？

**Comment by Biuuuuuuuu** [comment]
你好，感谢你的反馈。这个repo最初只是课程作业的一个存档，没有上传使用说明和数据（代码也写的比较放飞自我？）。我将在稍后更新。

**Comment by Biuuuuuuuu** [comment]
已经添加了一个说明文档：[https://github.com/Biuuuuuuuu/CYK-parser/blob/master/readme.txt](url)
